{{ $root := . }}
{{ if $root.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "report-platform.fullname" $root }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ $root.Values.ingress.className | quote }}
spec:
  rules:
{{ range $i, $host := $root.Values.ingress.hosts }}
  - host: {{ $host.host | quote }}
    http:
      paths:
{{ range $j, $p := $host.paths }}
      - path: {{ $p.path | quote }}
        pathType: {{ $p.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ printf "%s-%s" (include "report-platform.fullname" $root) ($p.backend | default "report-generation-service") }}
            port:
              number: {{ index $root.Values.services ($p.backend | default "report-generation-service") "port" }}
{{ end }}
{{ end }}
{{ end }}
