{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "report-platform.fullname" $root }}-{{ $name }}-secret
  labels:
{{ include "report-platform.labels" $root | trim | indent 4 }}
    component: {{ $name }}
type: Opaque
stringData:
  {{- range $k, $v := $svc.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
