ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER report_owner IDENTIFIED BY "ReportOwnerPass123";
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO report_owner;

CREATE USER report_ro IDENTIFIED BY "ReportReadOnly123";
GRANT CREATE SESSION TO report_ro;

ALTER USER report_owner QUOTA UNLIMITED ON USERS;

CREATE TABLE report_owner.customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(120) NOT NULL,
    region VARCHAR2(50) NOT NULL
);

CREATE TABLE report_owner.sales_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    order_date DATE NOT NULL,
    amount NUMBER(12,2) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES report_owner.customers(customer_id)
);

INSERT INTO report_owner.customers (customer_name, region) VALUES ('Acme UK', 'UK');
INSERT INTO report_owner.customers (customer_name, region) VALUES ('Acme US', 'US');
INSERT INTO report_owner.customers (customer_name, region) VALUES ('Acme IN', 'IN');

INSERT INTO report_owner.sales_orders (customer_id, order_date, amount, status)
VALUES (1, DATE '2026-01-05', 12000.00, 'completed');
INSERT INTO report_owner.sales_orders (customer_id, order_date, amount, status)
VALUES (1, DATE '2026-01-12', 8700.00, 'completed');
INSERT INTO report_owner.sales_orders (customer_id, order_date, amount, status)
VALUES (2, DATE '2026-02-02', 19100.00, 'completed');
INSERT INTO report_owner.sales_orders (customer_id, order_date, amount, status)
VALUES (3, DATE '2026-02-15', 6400.00, 'pending');
INSERT INTO report_owner.sales_orders (customer_id, order_date, amount, status)
VALUES (2, DATE '2026-03-03', 22150.00, 'completed');

GRANT SELECT ON report_owner.customers TO report_ro;
GRANT SELECT ON report_owner.sales_orders TO report_ro;
