flyway.url=jdbc:postgresql://localhost:5432/report_platform
flyway.user=admin
flyway.password=postgres-dev-password
flyway.locations=filesystem:postgres/migrations/flyway/sql
flyway.baselineOnMigrate=true
flyway.cleanDisabled=false
flyway.validateOnMigrate=true
